# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

dam:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-15 23:00
  time_step: 1h
  save_frequency_hours: null
  learning_mode: True

  learning_config:
    continue_learning: False
    trained_policies_save_path: null
    max_bid_price: 200
    algorithm: matd3
    actor_architecture: mlp
    learning_rate: 0.0001
    training_episodes: 30
    episodes_collecting_initial_experience: 5
    train_freq: 24h
    gradient_steps: -1
    batch_size: 128
    gamma: 0.99
    device: cuda:0
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    order_types: ["SB", "BB", "LB"]
    early_stopping_steps: 10
    early_stopping_threshold: 0.05

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 24h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear_complex
      additional_fields:
        - bid_type
        - min_acceptance_ratio
        - parent_bid_id
      param_dict:
        solver: glpk

tiny:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-02 00:00
  time_step: 1h
  save_frequency_hours: 24
  learning_mode: True

  learning_config:
    continue_learning: True
    trained_policies_save_path: null
    max_bid_price: 100
    algorithm: matd3
    actor_architecture: mlp
    learning_rate: 0.001
    training_episodes: 3
    episodes_collecting_initial_experience: 1
    train_freq: 24h
    gradient_steps: -1
    batch_size: 128
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 1

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
