# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base:
  start_date: 2035-01-01 00:00
  end_date: 2035-12-31 23:00
  time_step: 1h
  save_frequency_hours: 24

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2035-01-01 2:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 2h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    CRM_pos:
      operator: CRM_operator
      product_type: capacity_pos
      start_date: 2035-01-01 00:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 4h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_bid_volume: 100000
      maximum_bid_price: 9999
      minimum_bid_price: -9999
      price_unit: EUR/MW
      market_mechanism: pay_as_bid

    CRM_neg:
      operator: CRM_operator
      product_type: capacity_neg
      start_date: 2035-01-01 00:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 4h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_bid_volume: 100000
      maximum_bid_price: 9999
      minimum_bid_price: -9999
      price_unit: EUR/MW
      market_mechanism: pay_as_bid