# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base_case_2019:
  start_date: 2019-01-01 00:00
  end_date: 2019-12-31 00:00
  time_step: 1h
  industrial_dsm_units: null
  save_frequency_hours: 720

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-01-01 00:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

dam_case_2019:
  start_date: 2019-01-01 12:00
  end_date: 2019-02-01 00:00
  time_step: 1h
  industrial_dsm_units: null
  save_frequency_hours: 720

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-01-01 12:00
      products:
        - duration: 1h
          count: 24
          first_delivery: 24h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: complex_clearing
      param_dict:
        solver: highs
        pricing_mechanism: pay_as_clear
      additional_fields:
        - bid_type


eom_crm_case_2019:
  start_date: 2019-01-01 00:00
  end_date: 2019-12-31 00:00
  time_step: 1h
  industrial_dsm_units: null
  save_frequency_hours: 720

  bidding_strategy_params:
    crm_foresight: 4h

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-01-01 2:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 2h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    CRM_pos:
      operator: CRM_operator
      product_type: capacity_pos
      start_date: 2019-01-01 00:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 4h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_bid_volume: 100000
      maximum_bid_price: 9999
      minimum_bid_price: -9999
      price_unit: EUR/MW
      market_mechanism: pay_as_bid

    CRM_neg:
      operator: CRM_operator
      product_type: capacity_neg
      start_date: 2019-01-01 00:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 4h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_bid_volume: 100000
      maximum_bid_price: 9999
      minimum_bid_price: -9999
      price_unit: EUR/MW
      market_mechanism: pay_as_bid

base_case_2019_with_DSM:
  start_date: 2019-01-01 00:00
  end_date: 2019-02-01 00:00
  time_step: 1h
  industrial_dsm_units: industrial_dsm_units.csv
  save_frequency_hours: 720

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-01-01 00:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
