base_case_2019:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-11 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

crm_case_2019:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-11 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-01-01 01:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

    CRM_pos:
      operator: CRM_operator
      product_type: capacity_pos
      start_date: 2019-01-01 01:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 1h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid

    CRM_neg:
      operator: CRM_operator
      product_type: capacity_pos
      start_date: 2019-01-01 01:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 1h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
policy_case:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-11 00:00
  time_step: 1h
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
    CRM:
      operator: CRM_operator
      product_type: capacity
      start_date: 2018-12-31 20:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 4h
      opening_frequency: 4h
      opening_duration: 1h
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_bid
    # Policy market - contracts for next 7d 
    POL:
      operator: POL_operator
      product_type: energy
      start_date: 2018-12-31 20:00
      products:
        - duration: 7d
          count: 5
          first_delivery: 1d
      opening_frequency: 1d
      opening_duration: 1d
      volume_unit: MW
      maximum_volume: 1000000
      price_unit: EUR/MW
      market_mechanism: pay_as_clear