base_case:
  id: example_01
  start_date: 2019-01-01 00:00
  end_date: 2019-01-11 00:00
  time_step: 1h
  powerplants: powerplants.csv
  demand: inflex_demand.csv
  renewable_generation: renewable_generation.csv
  fuel_prices: fuel_prices.csv
  export_config:
    export_csv: True
    write_orders: True
    write_orders_frequency: 24
    write_capacities: True
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      duration: 1h
      count: 1
      first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear