base:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-31 00:00
  time_step: 1h
  save_frequency_hours: 24
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

dam:
  start_date: 2019-01-01 00:00
  end_date: 2019-04-01 00:00
  time_step: 1h
  save_frequency_hours: 24
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 1h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

dam_with_uc_clearing_rl:
  start_date: 2019-03-01 00:00
  end_date: 2019-03-05 00:00
  time_step: 1h
  save_frequency_hours: 24

  learning_config:
    observation_dimension: 50
    action_dimension: 24
    continue_learning: False
    load_model_path: None
    max_bid_price: 100
    learning_mode: True
    algorithm: matd3
    learning_rate: 0.001
    training_episodes: 10
    collecting_initial_experience: 2
    train_freq: 24
    gradient_steps: -1
    batch_size: 128
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 10

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 1h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: null
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: complex_uc_clearing

dam_with_uc_clearing:
  start_date: 2019-03-01 00:00
  end_date: 2019-03-05 00:00
  time_step: 1h
  save_frequency_hours: 24

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 1h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: null
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: complex_uc_clearing
